### ISSUE TITLE
research/project-interfaces

### ISSUE THREAD

**Issue by lbowes** [yar-sac/spaceport-america-cup#3]
### TODO
- [ ] Gather a comprehensive list of all equations that are relevant to the flight of a model rocket (ideally in a latex file, or folder of images, text document)
- [ ] From this,  extract a separate list of **all** unique physical quantities
- [ ] From the list above, extract another list containing **all** variables that _can be controlled in our design_ (all either can/cannot be controlled)
- [ ] Create a dependency graph with these variables with nodes being variables and edges representing a coupling between them in the equation (e.g. edges from both `m` and `a` to `F`)
